apiVersion: kubeeye.kubesphere.io/v1alpha1
kind: PluginSubscription
metadata:
  namespace: kubeeye-system
  name: kubebench
spec:
  # TODO(user): Add fields here
  enabled: false
---
apiVersion: kubeeye.kubesphere.io/v1alpha1
kind: PluginSubscription
metadata:
  namespace: kubeeye-system
  name: kubehunter
spec:
  # TODO(user): Add fields here
  enabled: true

