name: ci

on: [push, pull_request]

jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Downloading go dependencies
        run: go mod tidy

      - name: sync the vendor directory
        run: go mod vendor

      - name: Build command-line tool
        run: make buildke

      - uses: actions/upload-artifact@v2
        if: github.event_name == 'push'
        with:
          name: kubeeye
          path: kubeeye

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: panzhen666888/kubeeye
          tags: 0.0.2, latest
          registry: docker.io
          #dockerfile: Dockerfile.ci
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}